# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master] 

jobs:
  build:
    name: deploy to pages
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v1
        with:
         node-version: '10.x'
     - run: yarn install
     - run: yarn deploy
